name: 'dbtanalytics'
version: '1.0.0'
config-version: 2

profile: 'dbtanalytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  dbtanalytics:
    src:
      +materialized: view
    mart:
      +materialized: table
    staging:
      +materialized: view
