version: 2

sources:
  - name: dbt
    schema: source  # Replace with your source name
    tables:
      - name: visits_date_format
        identifier: source_dim_visit_logs_date_format
      - name: terms_classification
        identifier: source_unique_term_interest 
      - name: user_data
        identifier: source_user_data
      - name: search_terms
        identifier: source_search_terms